version: "3.8"
services: 
  backend:
    image: "surjo123/keeper_backend:v1"
    container_name: "backend_app"
    ports: 
      - "3000:3000"
    environment:
      MONGSTR: "your mongo string"
      JWTPWD: "jwt pwd"
      CLOUD_NAME: "your cloud name"
      CLOUD_API_KEY: "your cloud api key"
      CLOUD_API_SECRET: "your cloud api secret" 
    stdin_open: true
    tty: true
  frontend:
    build: .
    container_name: "frontend_app"
    ports: 
      - "5173:5173"
    environment:
      VITE_url: "http://localhost:3000"
    depends_on: 
      - "backend"
    volumes: 
      - "./src:/frontend_app/src"
    command: "npm run dev"
    stdin_open: true
    tty: true